### ISSUE TITLE
Strange issue on GitHub Actions.

### ISSUE THREAD

**Issue by jsi** [enonic/app-admin-home#342]
This build is very strange: https://github.com/enonic/app-admin-home/actions/runs/1119838065

It is building version 7.7.2. but fails because it can't download lib-admin version 7.7.3-SNAPSHOT.
Version 7.7.3-SNAPSHOT was checked in seconds later, but it is a different commit.  Also, the same build was done for the tag v7.7.2, and this passed.

**Comment by rymsha** [comment]
this build is checking out branch `refs/heads/7.7`, not a specific commit. at the moment it starts there is already 7.7.3-SNAPSHOT version specified (build is queued, so it is quite possible). From another side, XP 7.7.3-SNAPSHOT takes way much longer to be built and published in the repo. 

It is not really critical, because when XP 7.7.3-SNAPSHOT is published, app gets rebuilt anyway.

**Comment by jsi** [comment]
Okay.  That explains it, I guess this issue can be closed?  Did you spend a lot of time on it?    I have set this issue to Done, which means it will gain a point in the sprint tracker, but if it was really quick, maybe it should just be closed?

**Comment by rymsha** [comment]
Sime time was spent. So, let it be tracked
